/**
 * Rewrite TestSessionModal: list-based all-at-once input (efficient)
 * Uses string concatenation to avoid backtick issues in Node.js
 */
import { readFileSync, writeFileSync } from 'fs';

const filePath = 'src/app/admin/dashboard/classes/[id]/page.tsx';
let content = readFileSync(filePath, 'utf8');

// Find boundaries
const startMarker = '// \u2500\u2500\u2500 \ud14c\uc2a4\ud2b8 \uc138\uc158 \ubaa8\ub2ec (\uce7c\ub7fc\ud5e4\ub354 \ud14c\uc2a4\ud2b8 \ubc84\ud2bc) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500';
const endMarker   = 'function RolloverPopup(';

let startIdx = content.indexOf(startMarker);

// Also try the new marker if old not found
if (startIdx === -1) {
  const alt = '// \u2500\u2500\u2500 \ud14c\uc2a4\ud2b8 \uc138\uc158 \ubaa8\ub2ec (\uc804\uccb4 \ud559\uc0dd \uc77c\uad04 \uc785\ub825 \ubc29\uc2dd)';
  startIdx = content.indexOf(alt);
}

const endIdx = content.indexOf(endMarker);

if (startIdx === -1 || endIdx === -1) {
  console.log('Markers not found:', { startIdx, endIdx });
  // Print surrounding content for debugging
  const idx = content.indexOf('TestSessionModal');
  console.log('TestSessionModal found at:', idx);
  console.log('Context:', content.slice(idx - 100, idx + 200));
  process.exit(1);
}

console.log('Replacing from', startIdx, 'to', endIdx);

// Build new component as a raw string (no backtick issues)
const newComp = [
  '// \u2500\u2500\u2500 \ud14c\uc2a4\ud2b8 \uc138\uc158 \ubaa8\ub2ec (\uc804\uccb4 \ud559\uc0dd \uc77c\uad04 \uc785\ub825) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
  'type TestEntry = {',
  '  included: boolean;',
  '  score: string;',
  '  isPass: boolean | null;',
  '  noScoreReason: string;',
  '  rolloverDate: string;',
  '};',
  '',
  'function TestSessionModal({ session, students, existingSlot, existingChecks, onClose, onSaved }: {',
  '  session: ClassSession;',
  '  students: ClassStudent[];',
  '  existingSlot: HomeworkSlot | null;',
  '  existingChecks: Record<string, HomeworkCheck>;',
  '  onClose: () => void;',
  '  onSaved: (slot: HomeworkSlot, checks: Record<string, HomeworkCheck>) => void;',
  '}) {',
  "  const [testName, setTestName]   = useState(existingSlot?.title || '\ub2e8\uc5b4\ud14c\uc2a4\ud2b8');",
  "  const [testRange, setTestRange] = useState(existingSlot?.test_range || '');",
  "  const [maxScore, setMaxScore]   = useState(existingSlot?.max_score?.toString() || '');",
  "  const [passScore, setPassScore] = useState(existingSlot?.pass_score?.toString() || '');",
  '  const [isPF, setIsPF]           = useState(existingSlot?.is_pf ?? false);',
  '  const [saving, setSaving]       = useState(false);',
  '',
  '  const [entries, setEntries] = useState<Record<string, TestEntry>>(() => {',
  '    const init: Record<string, TestEntry> = {};',
  '    students.forEach(s => {',
  '      const c = existingChecks[s.student_name];',
  '      const wasSkipped = c?.status === \'skipped\';',
  '      init[s.student_name] = {',
  '        included:      c ? !wasSkipped : true,',
  "        score:         c?.score?.toString() || '',",
  '        isPass:        c?.is_pass ?? null,',
  "        noScoreReason: c?.delay_reason || '\uacb0\uc11d',",
  "        rolloverDate:  c?.rollover_date || '',",
  '      };',
  '    });',
  '    return init;',
  '  });',
  '',
  '  const updateEntry = (name: string, patch: Partial<TestEntry>) =>',
  '    setEntries(prev => ({ ...prev, [name]: { ...prev[name], ...patch } }));',
  '',
  '  const hasScore = (e: TestEntry) => isPF ? e.isPass !== null : e.score.trim() !== \'\';',
  '',
  '  const handleSave = async () => {',
  '    setSaving(true);',
  '    try {',
  '      let slot = existingSlot;',
  '      if (!slot) {',
  '        const [newSlot] = await createHomeworkSlotBatch([{',
  '          session_id: session.id,',
  "          title:      testName.trim() || '\ub2e8\uc5b4\ud14c\uc2a4\ud2b8',",
  "          hw_type:    'vocab_test',",
  '          test_range: testRange || null,',
  '          max_score:  maxScore  ? Number(maxScore)  : null,',
  '          pass_score: passScore ? Number(passScore) : null,',
  '          is_pf:      isPF,',
  '        }]);',
  '        slot = newSlot;',
  '      }',
  '      const newChecks: Record<string, HomeworkCheck> = {};',
  '      const includedStudents = students.filter(s => entries[s.student_name].included);',
  '      await Promise.all(includedStudents.map(async s => {',
  '        const e = entries[s.student_name];',
  '        const scoreFilled = hasScore(e);',
  '        const autoPass = !isPF && passScore && e.score ? Number(e.score) >= Number(passScore) : null;',
  '        const payload = scoreFilled ? {',
  '          slot_id: slot!.id, student_name: s.student_name, status: \'done\' as HwStatus,',
  '          score: !isPF && e.score ? Number(e.score) : null,',
  '          is_pass: isPF ? e.isPass : autoPass,',
  '          delay_reason: null, rollover_date: null,',
  '        } : {',
  '          slot_id: slot!.id, student_name: s.student_name, status: \'skipped\' as HwStatus,',
  '          score: null, is_pass: null,',
  '          delay_reason: e.noScoreReason,',
  '          rollover_date: e.rolloverDate || null,',
  '        };',
  '        await upsertHomeworkCheck(payload);',
  '        newChecks[s.student_name] = { ...(existingChecks[s.student_name] || {} as HomeworkCheck), ...payload };',
  '      }));',
  '      onSaved(slot!, newChecks);',
  '    } catch (err) { alert((err as Error).message); }',
  '    finally { setSaving(false); }',
  '  };',
  '',
  '  const includedCount  = students.filter(s => entries[s.student_name].included).length;',
  '  const completedCount = students.filter(s => { const e = entries[s.student_name]; return e.included && hasScore(e); }).length;',
  '',
  '  return (',
  '    <div className="fixed inset-0 backdrop-blur-sm z-[350] flex items-center justify-center p-4 animate-in fade-in duration-200"',
  "      style={{background: 'rgba(0,0,0,0.75)'}}>",
  '      <div className="w-full max-w-xl max-h-[92vh] rounded-2xl border flex flex-col shadow-2xl"',
  "        style={{background: '#111827', borderColor: 'rgba(99,102,241,0.3)'}}>",
  '',
  '        {/* \ud5e4\ub354 */}',
  '        <div className="flex items-center justify-between px-5 py-3.5 border-b shrink-0"',
  "          style={{borderColor: 'rgba(255,255,255,0.08)'}}>",
  '          <div>',
  '            <h3 className="text-[14px] font-black" style={{color: \'#e2e8f0\'}}>🎯 테스트 결과 기록</h3>',
  "            <p className=\"text-[10px] mt-0.5\" style={{color: '#6366f1'}}>",
  '              {session.session_date} · {includedCount}\uba85 \ud574\ub2f9 · {completedCount}\uba85 \uc785\ub825\uc644\ub8cc',
  '            </p>',
  '          </div>',
  "          <button onClick={onClose} className=\"p-1.5 rounded-lg transition-all\" style={{color: '#64748b'}}",
  "            onMouseEnter={e => (e.currentTarget.style.background='rgba(255,255,255,0.06)')}",
  "            onMouseLeave={e => (e.currentTarget.style.background='transparent')}>",
  '            <X size={14} />',
  '          </button>',
  '        </div>',
  '',
  '        {/* \ud14c\uc2a4\ud2b8 \uc124\uc815 */}',
  '        <div className="px-5 py-3 border-b shrink-0 space-y-2.5"',
  "          style={{borderColor: 'rgba(255,255,255,0.06)', background: 'rgba(99,102,241,0.05)'}}>",
  '          <div className="flex gap-2">',
  '            <input value={testName} onChange={e => setTestName(e.target.value)} placeholder="\ud14c\uc2a4\ud2b8\uba85"',
  '              className="flex-1 h-8 px-3 rounded-lg text-[12px] font-bold outline-none"',
  "              style={{background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)', color: '#c7d2fe'}} />",
  '            <input value={testRange} onChange={e => setTestRange(e.target.value)} placeholder="\ubc94\uc704 (L1~5 \ub3d9\uc758\uc5b4 \ub4f1)"',
  '              className="flex-1 h-8 px-3 rounded-lg text-[12px] outline-none"',
  "              style={{background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.2)', color: '#a5b4fc'}} />",
  '          </div>',
  '          <div className="flex items-center gap-3">',
  '            <div className="flex items-center gap-1.5">',
  '              <label className="text-[9px] font-black uppercase tracking-wider" style={{color: \'#818cf8\'}}>\ub9cc\uc810</label>',
  '              <input type="number" value={maxScore} onChange={e => setMaxScore(e.target.value)} placeholder="\u2014"',
  '                className="w-14 h-7 px-2 rounded-lg text-[12px] font-bold outline-none text-center"',
  "                style={{background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', color: '#e2e8f0'}} />",
  '            </div>',
  '            {!isPF && (',
  '              <div className="flex items-center gap-1.5">',
  '                <label className="text-[9px] font-black uppercase tracking-wider" style={{color: \'#f59e0b\'}}>\ucee4\ud2b8</label>',
  '                <input type="number" value={passScore} onChange={e => setPassScore(e.target.value)} placeholder="\u2014"',
  '                  className="w-14 h-7 px-2 rounded-lg text-[12px] font-bold outline-none text-center"',
  "                  style={{background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.2)', color: '#fcd34d'}} />",
  '              </div>',
  '            )}',
  '            <label className="flex items-center gap-1.5 cursor-pointer ml-auto px-2.5 py-1 rounded-lg select-none"',
  "              style={{background: isPF ? 'rgba(99,102,241,0.2)' : 'rgba(255,255,255,0.04)', border: isPF ? '1px solid rgba(99,102,241,0.4)' : '1px solid rgba(255,255,255,0.08)'}}>",
  '              <input type="checkbox" checked={isPF} onChange={e => setIsPF(e.target.checked)} className="w-3.5 h-3.5 rounded accent-indigo-500" />',
  '              <span className="text-[11px] font-black" style={{color: isPF ? \'#a5b4fc\' : \'#64748b\'}}>P/F \ubc29\uc2dd</span>',
  '            </label>',
  '          </div>',
  '        </div>',
  '',
  '        {/* \ud559\uc0dd \ubaa9\ub85d \uc804\uccb4 */}',
  '        <div className="flex-1 overflow-y-auto custom-scrollbar" style={{background: \'#0f172a\'}}>',
  '          {/* \ucf54\ub7fc \ud5e4\ub354 */}',
  '          <div className="flex items-center gap-2 px-4 py-2 border-b sticky top-0 z-10"',
  "            style={{background: '#0f172a', borderColor: 'rgba(255,255,255,0.06)'}}>",
  '            <div className="w-5 shrink-0" />',
  '            <div className="w-[90px] shrink-0 text-[9px] font-black uppercase tracking-widest" style={{color: \'#475569\'}}>\ud559\uc0dd</div>',
  '            <div className="flex-1 text-[9px] font-black text-center" style={{color: \'#475569\'}}>{isPF ? \'P / F\' : \'\uc810\uc218\'}</div>',
  '            <div className="w-[100px] shrink-0 text-[9px] font-black text-center" style={{color: \'#475569\'}}>\ubbf8\uc785\ub825 \uc0ac\uc720</div>',
  '            <div className="w-[90px] shrink-0 text-[9px] font-black text-center" style={{color: \'#475569\'}}>\uc5f0\uae30\uc77c</div>',
  '          </div>',
  '',
  '          {/* \ud559\uc0dd \ud589 */}',
  '          <div className="px-3 py-2 space-y-1">',
  '          {students.map((stu, si) => {',
  '            const e = entries[stu.student_name];',
  '            const scored = hasScore(e);',
  '            const autoPass = !isPF && passScore && e.score ? Number(e.score) >= Number(passScore) : null;',
  '            return (',
  '              <div key={stu.student_name}',
  '                className="flex items-center gap-2 px-2 py-1.5 rounded-xl transition-all"',
  '                style={{',
  "                  background: !e.included ? 'rgba(255,255,255,0.01)' : scored ? 'rgba(16,185,129,0.07)' : 'rgba(255,255,255,0.04)',",
  '                  opacity: e.included ? 1 : 0.3,',
  '                }}>',
  '',
  '                {/* \ud574\ub2f9\uc790 \uccb4\ud06c */}',
  '                <div className="w-5 shrink-0 flex justify-center">',
  '                  <input type="checkbox" checked={e.included}',
  '                    onChange={() => updateEntry(stu.student_name, { included: !e.included })}',
  '                    className="w-4 h-4 rounded cursor-pointer accent-indigo-500" />',
  '                </div>',
  '',
  '                {/* \uc774\ub984 */}',
  '                <div className="w-[90px] shrink-0">',
  "                  <p className=\"text-[12px] font-black truncate\" style={{color: e.included ? '#e2e8f0' : '#334155'}}>{stu.student_name}</p>",
  '                  {scored && !isPF && autoPass !== null && (',
  '                    <p className="text-[8px] font-black" style={{color: autoPass ? \'#34d399\' : \'#f87171\'}}>',
  "                      {autoPass ? '\ud1b5\uacfc' : '\ubbf8\ud1b5\uacfc(' + passScore + ')'}",
  '                    </p>',
  '                  )}',
  '                </div>',
  '',
  '                {/* \uc810\uc218 \uc785\ub825 */}',
  '                <div className="flex-1 flex justify-center">',
  '                  {e.included && (isPF ? (',
  '                    <div className="flex gap-1">',
  '                      <button onClick={() => updateEntry(stu.student_name, { isPass: true })}',
  '                        className="px-3 py-1 rounded-lg text-[10px] font-black transition-all"',
  '                        style={{',
  "                          background: e.isPass === true ? '#10b981' : 'rgba(16,185,129,0.1)',",
  "                          border: e.isPass === true ? '1px solid #10b981' : '1px solid rgba(16,185,129,0.25)',",
  "                          color: e.isPass === true ? 'white' : '#34d399',",
  '                        }}>P</button>',
  '                      <button onClick={() => updateEntry(stu.student_name, { isPass: false })}',
  '                        className="px-3 py-1 rounded-lg text-[10px] font-black transition-all"',
  '                        style={{',
  "                          background: e.isPass === false ? '#ef4444' : 'rgba(239,68,68,0.1)',",
  "                          border: e.isPass === false ? '1px solid #ef4444' : '1px solid rgba(239,68,68,0.25)',",
  "                          color: e.isPass === false ? 'white' : '#f87171',",
  '                        }}>F</button>',
  '                    </div>',
  '                  ) : (',
  '                    <div className="flex items-center gap-1">',
  '                      <input type="number" value={e.score}',
  '                        onChange={ev => updateEntry(stu.student_name, { score: ev.target.value })}',
  '                        placeholder="0" min={0} max={maxScore || undefined}',
  '                        className="w-16 h-7 rounded-lg text-[13px] font-black outline-none text-center"',
  '                        style={{',
  "                          background: e.score ? 'rgba(99,102,241,0.2)' : 'rgba(255,255,255,0.05)',",
  "                          border: e.score ? '1px solid rgba(99,102,241,0.5)' : '1px solid rgba(255,255,255,0.1)',",
  "                          color: '#c7d2fe',",
  '                        }} />',
  "                      {maxScore && <span className=\"text-[9px] font-bold\" style={{color: '#334155'}}>/{maxScore}</span>}",
  '                    </div>',
  '                  ))}',
  '                </div>',
  '',
  '                {/* \ubbf8\uc785\ub825 \uc0ac\uc720 */}',
  '                <div className="w-[100px] shrink-0">',
  '                  {e.included && !scored && (',
  '                    <select value={e.noScoreReason}',
  '                      onChange={ev => updateEntry(stu.student_name, { noScoreReason: ev.target.value })}',
  '                      className="w-full h-7 px-1.5 rounded-lg text-[10px] font-bold outline-none cursor-pointer"',
  '                      style={{',
  "                        background: 'rgba(239,68,68,0.12)',",
  "                        border: '1px solid rgba(239,68,68,0.25)',",
  "                        color: '#fca5a5',",
  '                        colorScheme: \'dark\',',
  '                      }}>',
  '                      <option value="\uacb0\uc11d">\uacb0\uc11d</option>',
  '                      <option value="\ubbf8\uc751\uc2dc">\ubbf8\uc751\uc2dc</option>',
  '                      <option value="\ubbf8\uc554\uae30">\ubbf8\uc554\uae30</option>',
  '                      <option value="\uae30\ud0c0">\uae30\ud0c0</option>',
  '                    </select>',
  '                  )}',
  '                </div>',
  '',
  '                {/* \uc5f0\uae30 \uc77c\uc790 */}',
  '                <div className="w-[90px] shrink-0">',
  '                  {e.included && !scored && (',
  '                    <input type="date" value={e.rolloverDate}',
  '                      onChange={ev => updateEntry(stu.student_name, { rolloverDate: ev.target.value })}',
  '                      className="w-full h-7 px-1.5 rounded-lg text-[9px] outline-none"',
  '                      style={{',
  "                        background: 'rgba(245,158,11,0.08)',",
  "                        border: '1px solid rgba(245,158,11,0.2)',",
  "                        color: '#fcd34d', colorScheme: 'dark',",
  '                      }} />',
  '                  )}',
  '                </div>',
  '              </div>',
  '            );',
  '          })}',
  '          </div>',
  '        </div>',
  '',
  '        {/* \uc800\uc7a5 \ubc84\ud2bc */}',
  '        <div className="px-5 py-3.5 border-t flex gap-3 shrink-0"',
  "          style={{borderColor: 'rgba(255,255,255,0.08)'}}>",
  '          <button onClick={onClose}',
  '            className="flex-1 h-10 rounded-xl text-[13px] font-black transition-all"',
  "            style={{border: '1px solid rgba(255,255,255,0.1)', color: '#64748b'}}>",
  '            \ucde8\uc18c',
  '          </button>',
  '          <button onClick={handleSave} disabled={saving || includedCount === 0}',
  '            className="flex-1 h-10 rounded-xl text-[13px] font-black transition-all disabled:opacity-30"',
  "            style={{background: 'linear-gradient(135deg,#6366f1,#4f46e5)', color: 'white'}}>",
  "            {saving ? '\uc800\uc7a5 \uc911...' : '\uc800\uc7a5 (' + includedCount + '\uba85)'}",
  '          </button>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  '',
  '',
].join('\n');

const before = content.slice(0, startIdx);
const after  = content.slice(endIdx);
content = before + newComp + after;

writeFileSync(filePath, content, 'utf8');
console.log('✅ TestSessionModal rewritten successfully');
console.log('File size:', content.length);
